# Generated by Django 3.2.7 on 2021-09-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('userPass', models.CharField(max_length=20)),
                ('userBirth', models.CharField(max_length=10)),
                ('userWeight', models.CharField(max_length=5)),
                ('userHeight', models.CharField(max_length=5)),
            ],
        ),
    ]
