# Generated by Django 3.2.7 on 2021-09-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userPass',
            new_name='user_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userHeight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userWeight',
        ),
    ]
