# Generated by Django 3.2.7 on 2021-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210923_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userBirth',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='userHeight',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='userWeight',
            field=models.CharField(default='', max_length=5),
        ),
    ]
